### ISSUE TITLE
Changed image position not work

### ISSUE THREAD

**Issue by JitenNumberTank** [BelooS/CircleToRect-ActivityTransition#1]
I have changed image position. circle image place at top let and rectagle image place at center of screen and scaletype change to fitCenter but its not working as its displayed in demo. its got problem.

**Comment by Oleg-Beloy** [comment]
Yes, you are right. Ty for notice. It have been fixed already, see updated repository
You can try, in the second activity xml:
`<com.example.beloo.circlerectbitmapanimator.view.CircleRectView
            android:id="@+id/circleView"
            android:transitionName="@string/circle"
            android:visibility="visible"
            android:layout_width="match_parent"
            android:layout_height="150dp"
            app:circleRadius="25dp"
            android:src="@drawable/picture"
            android:scaleType="centerCrop"
            tools:visibility="visible"
            android:layout_gravity="center_vertical"
            />`

In the first : 
`<com.example.beloo.circlerectbitmapanimator.view.CircleRectView
        android:id="@+id/circleView"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_below="@+id/toolbar"
        android:transitionName="@string/circle"
        app:circleRadius="25dp"
        android:src="@drawable/picture"
        android:scaleType="centerCrop"
        />`

**Comment by JitenNumberTank** [comment]
Thanks for your library. but my requirement is a bit different. Could you provide for dynamic position? it need to be transition from any position.

**Comment by Oleg-Beloy** [comment]
Check it, i think last update should fullfill your needs. Maybe it couldn't work in some specific case, but i'm not able to find any.  By the way, it's not a library, it's a just a custom rect/circle view & custom movement transition sample. 
PS: also you could try to exclude custom transition at all. Remove setup logic from `SecondActivity` and it will be working via default way. Duration of transition you could set like here http://stackoverflow.com/questions/35715144/activityoptionscompat-makescenetransitionanimation-with-custom-duration
